version: 0.0.1
pathURL : http://localhost:8000
server:
  applicationConnectors:
  - type: http
    port: 9006
  adminConnectors:
  - type: http
    port: 9007
    
swagger:
  resourcePackage: com.morrisons.esel.price.resources
  title: "Price Service" 
  version: "0.0.1"
  description: "Price of the product"

logging:
  level: DEBUG
  loggers:
    io.dropwizard: DEBUG
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: STDOUT
      logFormat: "%-5level [%date] %logger: %message \n"
    - type: file
      currentLogFilename: logs/range-service.log
      threshold: ALL
      archive: true
      archivedLogFilenamePattern: logs/range-service_%d.log
      archivedFileCount: 14
      timeZone: Europe/London
      logFormat: "%-5level [%date] %logger: %message \n"     